options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # get cluster creds
  - id: "get cluster creds"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_OPS_REGION --project $_OPS_PROJECT_ID
 
  # Get Pub/Sub message
  - id: "Get Pub/Sub message"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        gcloud pubsub subscriptions pull "projects/$_OPS_PROJECT_ID/subscriptions/$_OPS_PREFIX-team-create-sub" --format=json --auto-ack | grep data | awk -F'"' '/"data"/ {print $4}' | base64 -d > /workspace/teamsa.txt

  # Create role binding
  - id: "IAM role container.viewer"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        service_account_name=$(cat /workspace/teamsa.txt)

        gcloud projects add-iam-policy-binding $_OPS_PROJECT_ID \
        --member=serviceAccount:${service_account_name} \
        --role=roles/container.viewer

  # create team namespace
  - id: "create team namespace"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        service_account_name=$(cat /workspace/teamsa.txt)

        # Extract teamname and teamprojected
        teamname=$(echo "$service_account_name" | awk -F'[@.]' '{print $1}')
        teamprojectid=$(echo "$service_account_name" | awk -F'[@.]' '{print $2}')
        
        # Merge teamname and teamprojectid
        team_namespace="${teamname}-${teamprojectid}"

        # Create Kubernetes namespace
        kubectl create namespace "$team_namespace"

  # Create role
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        service_account_name=$(cat /workspace/teamsa.txt)

        # Extract teamname and teamprojected
        teamname=$(echo "$service_account_name" | awk -F'[@.]' '{print $1}')
        teamprojectid=$(echo "$service_account_name" | awk -F'[@.]' '{print $2}')
        
        # Merge teamname and teamprojectid
        team_namespace="${teamname}-${teamprojectid}"

        #actual role creation
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: ${team_namespace}-role
          namespace: $team_namespace
        rules:
        - apiGroups: [""]
          resources: ["*"]
          verbs: ["*"]
        EOF

  # Create role binding
  - id: "Create role binding"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        service_account_name=$(cat /workspace/teamsa.txt)

        # Extract teamname and teamprojected
        teamname=$(echo "$service_account_name" | awk -F'[@.]' '{print $1}')
        teamprojectid=$(echo "$service_account_name" | awk -F'[@.]' '{print $2}')
        
        # Merge teamname and teamprojectid
        team_namespace="${teamname}-${teamprojectid}"

        # Create role binding
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: ${team_namespace}-binding
          namespace: $team_namespace
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: ${team_namespace}-role
        subjects:
        - kind: User
          name: "${service_account_name}"
        EOF
  # create team namespace
  - id: "create team namespace"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -x
      - -c
      - |
        #!/bin/bash
        service_account_name=$(cat /workspace/teamsa.txt)

        # Extract teamname and teamprojected
        teamname=$(echo "$service_account_name" | awk -F'[@.]' '{print $1}')
        teamprojectid=$(echo "$service_account_name" | awk -F'[@.]' '{print $2}')
        
        # Merge teamname and teamprojectid
        team_namespace="${teamname}-${teamprojectid}"

        # Create a secret for the team
        gcloud secrets create "$team_namespace" --project="$_OPS_PROJECT_ID"

        # Add the secret data (replace 'your-secret-data' with actual secret data)
        echo -n "your-secret-data" | gcloud secrets versions add "$team" --data-file=- --project="$_OPS_PROJECT_ID"
