apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: tagger-gcp-coe-msp-sandbox
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: gubgub-db
  namespace: tagger-gcp-coe-msp-sandbox
spec:
  restartPolicy: Always
  containers:
  - name: db
    image: mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: game_db
    - name: MYSQL_ROOT_PASSWORD
      value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gubgub-frontend
  namespace: tagger-gcp-coe-msp-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/abel-ghack-infra/ghack-docker-repo/gubgub:latest
        ports:
        - containerPort: 5000
 #       env:
 #       - name: MYSQL_PASSWORD
  #        value: password
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: tagger-gcp-coe-msp-sandbox
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app

#kubectl create deployment my-deployment --image=europe-west1-docker.pkg.dev/abel-ghack-infra/ghack-docker-repo/gubgub:latest --port=5000 --namespace=tagger-gcp-coe-msp-sandbox --dry-run=client -o yaml --save-config > deployment.yaml
