apiVersion: apps/v1
kind: Deployment
metadata:
  name: gubgub-frontend
  namespace: tagger-gcp-coe-msp-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/abel-ghack-infra/ghack-docker-repo/gubgub:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password