version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5550:5000"
    environment:
      MYSQL_PASSWORD: 111b0db2129e7527cece3429333ac026
    depends_on:
      - db
    networks:
      - game-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_ROOT_PASSWORD: 111b0db2129e7527cece3429333ac026
    ports:
      - "3306:3306"
    networks:
      - game-network
networks:
  game-network:
