version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5550:5000"
    environment:
      MYSQL_PASSWORD: password
    depends_on:
      - db
    networks:
      - game-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - game-network
networks:
  game-network:
