version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5550:5000"
    environment:
      MYSQL_PASSWORD: "tmppassword"
    depends_on:
      - db-svc
    networks:
      - game-network
  db-svc:
    build:
      context: ../app_db
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    networks:
      - game-network
networks:
  game-network:
