apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: nanann
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: gubgub
  namespace: nanann
spec:
  restartPolicy: Always
  containers:
  - name: db
    image: mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: game_db
    - name: MYSQL_ROOT_PASSWORD
      value: password
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app
  name: gubgubapp
  namespace: nanann
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: myimage
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: nanann
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app
