apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"gubgub-frontend","namespace":"dispatcher-gcp-coe-msp-sandbox"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"app"}},"template":{"metadata":{"labels":{"app":"app"}},"spec":{"containers":[{"env":[{"name":"MYSQL_PASSWORD","value":"IHateThisGame"}],"image":"europe-west1-docker.pkg.dev/abel-ghack-infra/ghack-docker-repo/gubgub:latest","name":"app","ports":[{"containerPort":5000}]}]}}}}
  creationTimestamp: "2024-02-24T13:52:11Z"
  generation: 1
  name: gubgub-frontend
  namespace: dispatcher-gcp-coe-msp-sandbox
  resourceVersion: "19478"
  uid: 9994fc79-4505-4748-9bfa-aee2b08bc035
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: MYSQL_PASSWORD
          value: "111b0db2129e7527cece3429333ac026"
        image: europe-west1-docker.pkg.dev/abel-ghack-infra/ghack-docker-repo/gubgub:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-02-24T13:52:12Z"
    lastUpdateTime: "2024-02-24T13:52:12Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-02-24T13:52:12Z"
    lastUpdateTime: "2024-02-24T13:52:12Z"
    message: ReplicaSet "gubgub-frontend-69c447f775" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
